name: Generate Atom feed

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Update-Atom:
    if: github.repository == 'neos-modding-group/neos-mod-manifest'
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v3

      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: neos-modding-group/neos-modding-group.github.io
          path: gh-pages
          ssh-key: ${{ secrets.PAGES_AUTH }}

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: append to Atom feed
        env:
          REF_BASE: ${{ github.base_ref || format('{0}~', github.sha) }}
          REF_NEW: ${{ github.head_ref || github.sha }}
        run: |
          pip3 install -r requirements.txt
          python3 atom_feeder.py

      - name: commit
        env:
          PAGES_AUTH: ${{ secrets.PAGES_AUTH }}
        run: |
          cd gh-pages
          git diff --quiet --exit-code feed.xml && exit 0
          mkdir -p "~/.ssh"
          echo "$PAGES_AUTH" > "~/.ssh/id_rsa"
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add --force feed.xml
          git commit -m "Update Atom feed"
          git push origin master
