name: Generate mods list markdown

on:
  push:
    branches:
      - master

jobs:
  Generate-Markdown:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate readme
        run: ./gen_readme.py

      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: commit
        run: |
          git add --force README.md
          git commit -m "Update mods list"
          git push origin master
