name: Generate mods list markdown

on:
  push:
    branches:
      - master

jobs:
  Generate-Markdown:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          path: master

      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
    
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3"

      - name: generate readme
        run: ./master/gen_readme.py

      - name: enter gh-pages directory
        run: cd gh-pages

      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: commit
        run: |
          git add --force mod-list.md
          git commit -m "Update mod list"
          git push origin gh-pages
